---
title: 'Unit 11: Modeling Financial Data'
author: "Randall Hendrickson"
date: "November 6, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Description: Unit 11: Modeling Financial Data
 

```{r testing}

#install.packages("tseries")
library(tseries)

## S&P 500 (^GSPC)
###    SNP - SNP Real Time Price. Currency in USD

# Download the data of SP500 '^gspc'.
SNPdata <- get.hist.quote("^GSPC",quote="Close")

# Calculate the log returns, which is the subtraction of log(lag(SNPdata)) and log(SNPdata)
SNPret <- log(lag(SNPdata)) - log(SNPdata)

# Calculate volatility measure that is to multiply sd(SNPret),sqrt(250), 100
# 250 is approx. number of trading days in a year
SNPvol <- sd(SNPret) * sqrt(250) * 100

## Define getVol function for volatility
getVol <- function(d, logrets) {
	var = 0
	lam = 0
	varlist <- c()

	for (r in logrets) {
		lam = lam*(1 - 1/d) + 1
	  var = (1 - 1/lam)*var + (1/lam)*r^2
		varlist <- c(varlist, var)
	}

	sqrt(varlist)
}

# recreate Figure 6.12 in the text on page 155
# Calculate volatility over entire length of series for various three different decay factors: 10 30. 100
#volest <- getVol(10, SNPret)

# call getVol function with the parameters: 10,SNPret
volest <- getVol(10, SNPret)

# call getVol function with the parameters: 30,SNPret
volest2 <- getVol(30, SNPret)

# call getVol function with the parameters: 100,SNPret
volest3 <- getVol(100, SNPret)

# Plot the results, overlaying the volatility curves on the data, just as was done in the S&P example.
plot(volest ,type="l")

# Add connected line segments for volest2 with the parameters: type="l",col="red"
lines(volest2, type="l", col="red")

# Add connected line segments for volest3 with the parameters: type="l",col="blue"
lines(volest3, type="l", col="blue")

```



```{r testing2}

# Download the data of MSFT 'MSFT'.
StockData <- get.hist.quote("MSFT",quote="Close")

# Calculate the log returns, which is the subtraction of log(lag(StockData)) and log(StockData)
Sret <- log(lag(StockData)) - log(StockData)

# Calculate volatility measure that is to multiply sd(Sret),sqrt(250), 100
# 250 is approx. number of trading days in a year
Svol <- sd(Sret) * sqrt(250) * 100

## Define getVol function for volatility
getVol <- function(d, logrets) {
	var = 0
	lam = 0
	varlist <- c()

	for (r in logrets) {
		lam = lam*(1 - 1/d) + 1
	  var = (1 - 1/lam)*var + (1/lam)*r^2
		varlist <- c(varlist, var)
	}

	sqrt(varlist)
}

# call getVol function with the parameters: 10,Sret
volest <- getVol(10, Sret)

# call getVol function with the parameters: 30,Sret
volest2 <- getVol(30, Sret)

# call getVol function with the parameters: 100,Sret
volest3 <- getVol(100, Sret)

# Plot the results, overlaying the volatility curves on the data, just as was done in the S&P example.
plot(volest ,type="l")

# Add connected line segments for volest2 with the parameters: type="l",col="red"
lines(volest2, type="l", col="red")

# Add connected line segments for volest3 with the parameters: type="l",col="blue"
lines(volest3, type="l", col="blue")

```

